// Mega

#pragma once

#ifndef SHADER_STAGES_H
#define SHADER_STAGES_H

enum SHADER_STAGE { VERTEX_STAGE, HULL_STAGE, DOMAIN_STAGE, GEOMETRY_STAGE, PIXEL_STAGE, UNKNOWN_STAGE };

#endif /* SHADER_STAGES_H */